site_name: HabershonLab research guide
site_url: https://HabershonLab.github.io/research-guide
site_author: Scott Habershon
repo_url: https://github.com/HabershonLab/research-guide
edit_uri: ""

nav:
  - Home: index.md
  - Basic graphs: Graphs.ipynb
  - Computing help: computing.md
  
theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - content.code.copy
  palette:
    - scheme: default
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.tabbed
  - toc:
      permalink: true

plugins:
  - search
  - mkdocs-jupyter:
      execute: false
