site_name: mkdocs-jupyterlite
site_url: https://nickcrews.github.io/mkdocs-jupyterlite/
repo_url: https://github.com/nickcrews/mkdocs-jupyterlite/

nav:
  - Home: index.md
  - Notebook In Root: notebook.ipynb
  - Directory:
      - Notebook In Directory: directory/notebook.ipynb

markdown_extensions:
  - pymdownx.snippets:
      check_paths: true

extra_css:
  - extra.css

plugins:
  - jupyterlite:
      enabled: true
      notebook_patterns:
        - '*.ipynb'
